### ISSUE TITLE
Opening in default search engine instead of google

### ISSUE THREAD

**Issue by Dostoi** [ivovk/Axon#1]
Is it possible to open in the default search engine instead of google when clicking on more ?

**Comment by ivovk** [comment]
Yes, but not through settings. You could unzip the axon.xpi file and edit listeners.js. Around line 50 in https://github.com/ivovk/Axon/blob/master/Firefox/data/listeners.js you will see the following block:

 // Wordnik, Wikipedia and Google Maps URLs
const SEARCH_URL_WORDNIK = "https://www.wordnik.com/words/";
const GOOGLE_DEFINE_URL = "https://www.google.com/search?hl=en&q=define+"
const GOOGLE_NORMAL_URL = "https://www.google.com/search?q="

To change all the More links to Yahoo for instance, change the constants as follows:

const SEARCH_URL_WORDNIK = "https://search.yahoo.com/search?p=";
const GOOGLE_DEFINE_URL = "https://search.yahoo.com/search?p="
const GOOGLE_NORMAL_URL = "https://search.yahoo.com/search?p="

**Comment by ivovk** [comment]
Yes the new version opens the default search engine when clicking on more: https://addons.mozilla.org/en-US/firefox/addon/axon/versions/2.6

**Comment by Dostoi** [comment]
Nice :)
