### ISSUE TITLE
Wiktionary with different languages

### ISSUE THREAD

**Issue by bricewge** [ivovk/Axon#2]
It would be great to set the language of the wiktionary to something other than English.
For example when I have set my primary Wikipedia language as French, when I select a French world I would like to seen th wikitionary French page show up and not the English one (when the world is similar to French).

**Comment by ivovk** [comment]
A Wiktionary page has no inherent structure. Every language would require a different parser. Or a 'raw dump' of the Wiktionary page content.
Maybe this add-on has what you're looking for: https://addons.mozilla.org/nl/firefox/addon/google-dictionary-and-google-t/

Wiktionary links:
https://fr.wiktionary.org/wiki/chaise 
https://es.wiktionary.org/wiki/silla
http://fr.wiktionary.org/w/api.php?format=xml&action=query&prop=extracts&redirects=1&titles=chaise
http://es.wiktionary.org/w/api.php?format=xml&action=query&prop=extracts&redirects=1&titles=silla
http://htmledit.squarefree.com/

**Comment by ivovk** [comment]
You can set the Wiktionary to any language in the new version: https://addons.mozilla.org/en-US/firefox/addon/axon/versions/2.6

**Comment by bricewge** [comment]
Thanks for the fix!

**Comment by ivovk** [comment]
My pleasure!
