### ISSUE TITLE
Why is firefox saying that the last version is 2.6.3 ?

### ISSUE THREAD

**Issue by Dostoi** [ivovk/Axon#4]
On the addon page (https://addons.mozilla.org/en-US/firefox/addon/axon/) the last version is 2.6.3 but on github it's 2.6.2.
Is it normal ?

**Comment by ivovk** [comment]
The 2.6.2 had debug mode turned on which turnes the tab text color red and overwrites some configuration settings. Uploading a different 2.6.2 is not allowed so I turned off debugging and uploaded it as 2.6.3.

**Comment by Dostoi** [comment]
Thanks for the explanation

**Comment by ivovk** [comment]
Sure no prob
