### ISSUE TITLE
No more option to use wikipedia only

### ISSUE THREAD

**Issue by Dostoi** [ivovk/Axon#5]
With the last version 2.6.3, there isn't any option to use only wikipedia. Is it normal too ? ^^

**Comment by ivovk** [comment]
I figured you can now click on the title to see Wikipedia, but I'll add the option back in with the next release.

**Comment by Dostoi** [comment]
Didn't know you can do that my bad

**Comment by ivovk** [comment]
I think I removed the explanation from the homepage sorry about that
