### ISSUE TITLE
Allow the use of openstreetmap instead of google map

### ISSUE THREAD

**Issue by Dostoi** [ivovk/Axon#6]
Is it possible to had it as an option to use openstreetmap instead of google map ?

**Comment by ivovk** [comment]
Google maps is already working. I'm not sure openstreetmap would add anything extra.

**Comment by Dostoi** [comment]
Ho yes, I'm not telling it's not working. On the contrary, it's a great feature and working very well.
It's just a philosophical thing (don't know how to tell it exactly), to be able to avoid the use of google service and use only free service.
But I can understand if you don't want to bother to develop this, there's no problem with that :)

**Comment by ivovk** [comment]
There are several options to consider for future releases.

Openlayers API + openstreetmap
http://wiki.openstreetmap.org/wiki/OpenLayers
https://www.linux.org.au/conf/2006/speakerb540.html?id=297

Mapbox + openstreetmap 
https://www.mapbox.com/guides/osm-and-mapbox/

Google maps API + openstreetmap
http://wiki.openstreetmap.org/wiki/Google_Maps_Example

Skobbler maps API + openstreetmap
http://maps.skobbler.com

Links
http://googlemapsmania.blogspot.nl/2005_06_01_archive.html
http://geoserver.org
http://qgis.org
http://gis.stackexchange.com/questions/26800/whats-the-difference-in-using-openlayers-and-mapbox

**Comment by Dostoi** [comment]
What you're listing is the list of different choice you want to give to the user ?
Choosing between Mapbox or openstreetmap for example ?
Or using mapbox and opentstreetmap together as an alternative to what's already there ?

**Comment by ivovk** [comment]
I've listed possible replacements for Google maps. I'm not sure the maps and APIs differ enough to provide multiple options. Google maps works just fine but it is something to consider for future releases.

**Comment by Dostoi** [comment]
Ok, well then I'll go against the 3rd one using the google api.
From the link you shared the first one seems better but I don't know a lot in all that so I can't help much ^^
